/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotelmanagement.view.reservation;

/**
 *
 * @author User
 */
public class ReservationManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReservationManagementPanel
     */
    public ReservationManagementPanel() {
        initComponents();
        com.hotelmanagement.util.UIUtils.applyTheme(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbGuest = new javax.swing.JComboBox<>();
        txtNumberOfGuests = new javax.swing.JTextField();
        cmbRoom = new javax.swing.JComboBox<>();
        cmbReservationStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSpecialRequests = new javax.swing.JTextArea();
        txtSearchReservation = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reservation Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 14, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Guest:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 107, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Checki-in-date:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 191, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Number of guests:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 272, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Room type:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 148, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Check-out-date:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 224, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Raservation Status:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 316, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Special Request:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 357, -1, -1));

        cmbGuest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbGuest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 101, 105, -1));

        txtNumberOfGuests.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtNumberOfGuests, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 269, 77, -1));

        cmbRoom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 145, 105, -1));

        cmbReservationStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbReservationStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Confirmed", "Checked In", "Checked Out", "Cancelled" }));
        add(cmbReservationStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 313, -1, -1));

        txtSpecialRequests.setColumns(20);
        txtSpecialRequests.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSpecialRequests.setRows(5);
        jScrollPane1.setViewportView(txtSpecialRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 367, 229, 71));

        txtSearchReservation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtSearchReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 15, 161, -1));

        btnSearch.setBackground(new java.awt.Color(102, 255, 102));
        btnSearch.setText("Search");
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 59, -1, -1));

        btnBook.setBackground(new java.awt.Color(255, 255, 102));
        btnBook.setText("Book");
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 102));
        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        btnCancel.setBackground(new java.awt.Color(255, 204, 51));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 153, 51));
        btnClear.setText("Clear");
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        btnback.setBackground(new java.awt.Color(255, 153, 51));
        btnback.setText("Back");
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Reservation id ", "Guest", "Check-in-date", "check-out-date", "Number of guests", "Reservation Status", "Special Request"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 14, 977, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Reservation id:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 59, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 59, 116, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 189, 115, -1));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 229, 115, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cmbGuest;
    private javax.swing.JComboBox<String> cmbReservationStatus;
    private javax.swing.JComboBox<String> cmbRoom;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtNumberOfGuests;
    private javax.swing.JTextField txtSearchReservation;
    private javax.swing.JTextArea txtSpecialRequests;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnBook() { return btnBook; }
    public javax.swing.JButton getBtnCancel() { return btnCancel; }
    public javax.swing.JButton getBtnClear() { return btnClear; }
    public javax.swing.JButton getBtnSearch() { return btnSearch; }
    public javax.swing.JButton getBtnUpdate() { return btnUpdate; }
    public javax.swing.JButton getBtnBack() { return btnback; }
    public javax.swing.JComboBox<String> getCmbGuest() { return cmbGuest; }
    public javax.swing.JComboBox<String> getCmbStatus() { return cmbReservationStatus; }
    public javax.swing.JComboBox<String> getCmbRoom() { return cmbRoom; }
    public javax.swing.JTable getTable() { return jTable1; }
    public javax.swing.JTextField getTxtNumberOfGuests() { return txtNumberOfGuests; }
    public javax.swing.JTextField getTxtSearch() { return txtSearchReservation; }
    public javax.swing.JTextArea getTxtSpecialRequests() { return txtSpecialRequests; }
    public com.toedter.calendar.JDateChooser getDpCheckIn() { return jDateChooser1; }
    public com.toedter.calendar.JDateChooser getDpCheckOut() { return jDateChooser2; }
}
