# Database Configuration
db.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=HotelManagementDB;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=Sa@12345
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver