/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotelmanagement.view.employee;

/**
 *
 * @author User
 */
public class employeemanagementpanel extends javax.swing.JPanel {

    /**
     * Creates new form employeemanagementpanel
     */
    public employeemanagementpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtNIC = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbDepartment = new javax.swing.JComboBox<>();
        txtPosition = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        dpHireDate = new com.toedter.calendar.JDateChooser();
        cmbEmploymentStatus = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1107, 457));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Employee Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("First name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 89, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Last name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 186, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Date of birth:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 227, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("NIC:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 268, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Phone:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 312, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 356, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Department:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 397, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Position:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 438, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Salary:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 482, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Hire date:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 523, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Employee status:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 563, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Employee id:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, -1, -1));

        txtEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 48, 140, -1));

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 86, 140, -1));

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 139, 140, -1));

        cmbGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 183, 140, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 225, 140, -1));

        txtNIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 265, 140, -1));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 309, 140, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 353, 140, -1));

        cmbDepartment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Management", "Front Office", "Housekeeping", "Finance", "Food & Beverage", "Security" }));
        add(cmbDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 391, 140, -1));

        txtPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 435, 140, -1));

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 479, 140, -1));
        add(dpHireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 523, 140, -1));

        cmbEmploymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "OnLeave", "Terminated", "Suspended" }));
        add(cmbEmploymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 563, 126, -1));

        txtsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 16, 149, -1));

        btnsearch.setBackground(new java.awt.Color(102, 255, 102));
        btnsearch.setText("Search");
        add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 51, -1, -1));

        btnAdd.setBackground(new java.awt.Color(255, 255, 102));
        btnAdd.setText("Add");
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 101, -1, -1));

        btnupdate.setBackground(new java.awt.Color(255, 255, 102));
        btnupdate.setText("Update");
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 142, -1, -1));

        btndelete.setBackground(new java.awt.Color(255, 102, 51));
        btndelete.setText("Delete");
        add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 183, -1, -1));

        btnclear.setBackground(new java.awt.Color(255, 153, 51));
        btnclear.setText("Clear");
        add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 224, -1, -1));

        btnback.setBackground(new java.awt.Color(255, 204, 51));
        btnback.setText("Back");
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 268, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Department", "Position", "Phone", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 0, 515, 585));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbEmploymentStatus;
    private javax.swing.JComboBox<String> cmbGender;
    private com.toedter.calendar.JDateChooser dpHireDate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnAdd() { return btnAdd; }
    public javax.swing.JButton getBtnBack() { return btnback; }
    public javax.swing.JButton getBtnClear() { return btnclear; }
    public javax.swing.JButton getBtnDelete() { return btndelete; }
    public javax.swing.JButton getBtnSearch() { return btnsearch; }
    public javax.swing.JButton getBtnUpdate() { return btnupdate; }
    public javax.swing.JComboBox<String> getCmbDepartment() { return cmbDepartment; }
    public javax.swing.JComboBox<String> getCmbEmploymentStatus() { return cmbEmploymentStatus; }
    public javax.swing.JComboBox<String> getCmbGender() { return cmbGender; }
    public com.toedter.calendar.JDateChooser getDpHireDate() { return dpHireDate; }
    public com.toedter.calendar.JDateChooser getDpDateOfBirth() { return jDateChooser1; }
    public javax.swing.JTable getTable() { return jTable1; }
    public javax.swing.JTextField getTxtEmail() { return txtEmail; }
    public javax.swing.JTextField getTxtEmployeeID() { return txtEmployeeID; }
    public javax.swing.JTextField getTxtFirstName() { return txtFirstName; }
    public javax.swing.JTextField getTxtLastName() { return txtLastName; }
    public javax.swing.JTextField getTxtNIC() { return txtNIC; }
    public javax.swing.JTextField getTxtPhone() { return txtPhone; }
    public javax.swing.JTextField getTxtPosition() { return txtPosition; }
    public javax.swing.JTextField getTxtSalary() { return txtSalary; }
    public javax.swing.JTextField getTxtSearch() { return txtsearch; }
}
